xpd-ldrd20-31:
  direct:
    authentication:
      allow_anonymous_access: true
    trees:
    - tree: databroker.mongo_normalized:Tree.from_uri
      path: /
      args:
        uri: mongodb://localhost:27017/metadatastore-local
        asset_registry_uri: mongodb://localhost:27017/asset-registry-local
