metadatastore:
  module: databroker.headersource.mongo
  class: MDS
  config:
    host: 'localhost'
    port: 27017
    database: 'metadatastore-local'
    timezone: 'US/Eastern'
assets:
  module: databroker.assets.mongo
  class: Registry
  config:
    host: 'localhost'
    port: 27017
    database: 'asset-registry-local'
